version: "3.9"
services:
  one:
    image: ubuntu/nginx
    build: .
    tty: true
    ports:
      - "8000:80"
    networks:
      - ha-network
    environment:
      - NGINX_PORT=80
    container_name: one

  two:
    image: ubuntu/nginx
    build: .
    tty: true
    ports:
      - "8001:80"
    networks:
      - ha-network
    environment:
      - NGINX_PORT=80
    container_name: two

  three:
    image: ubuntu/nginx
    build: .
    tty: true
    ports:
      - "8002:80"
    networks:
      - ha-network
    environment:
      - NGINX_PORT=80
    container_name: three

networks:
  ha-network:
    external: false
